# Generated by Django 3.0.7 on 2020-06-25 15:05

from django.db import migrations, models
import django.db.models.deletion
import retos.validators


class Migration(migrations.Migration):

    dependencies = [
        ('retos', '0003_usuarios_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField()),
                ('date', models.DateField(auto_now_add=True)),
                ('voice', models.FileField(blank=True, upload_to='imag_retos', validators=[retos.validators.validate_file_extension])),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='retos.Challenge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='retos.Usuarios')),
            ],
        ),
    ]
