# Generated by Django 3.0.7 on 2020-07-02 14:40

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('retos', '0012_auto_20200629_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='postuser',
            name='answer',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
