# Generated by Django 3.0.7 on 2020-07-02 21:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('retos', '0019_auto_20200702_2058'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuarios',
            options={},
        ),
        migrations.AlterModelManagers(
            name='usuarios',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='safe_question',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='user_language_learning',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='retos.Language_learning'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='user_language_native',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='retos.Language_native'),
        ),
    ]
