# Generated by Django 3.0.7 on 2020-07-02 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retos', '0024_auto_20200702_2335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
