# Generated by Django 3.0.7 on 2020-07-06 15:32

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('retos', '0025_auto_20200702_2336'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerChallenge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', ckeditor.fields.RichTextField()),
                ('date', models.DateField(auto_now_add=True)),
                ('postuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_post_user', to='retos.PostUser')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
