# Generated by Django 3.0.7 on 2020-07-20 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retos', '0027_answerchallenge_challenge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarios',
            name='user_language_learning',
        ),
        migrations.AddField(
            model_name='usuarios',
            name='user_language_learning',
            field=models.ManyToManyField(to='retos.Language_learning'),
        ),
    ]
