# Generated by Django 3.0.7 on 2020-07-23 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('retos', '0029_auto_20200720_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='user_language_learning',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='retos.Language_learning'),
        ),
        migrations.AddField(
            model_name='postuser',
            name='user_language_learning',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='retos.Language_learning'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='second_user_language_learnin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='second_language', to='retos.Language_learning'),
        ),
    ]
