# Generated by Django 3.0.7 on 2020-07-23 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('retos', '0030_auto_20200723_1506'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postuser',
            old_name='user_language_learning',
            new_name='user_language_native',
        ),
    ]
