# Generated by Django 3.0.8 on 2020-07-27 21:32

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        #('django_comments', '0003_add_submit_date_index'),
        ('retos', '0032_auto_20200723_1539'),
    ]

    operations = [
        migrations.CreateModel(
            name='MPTTComment',
            fields=[
                ('comment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='django_comments.Comment')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='retos.MPTTComment')),
            ],
            options={
                'ordering': ['tree_id', 'lft'],
            },
            bases=('django_comments.comment', models.Model),
        ),
    ]
