# Generated by Django 3.0.8 on 2020-07-27 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        #('django_comments', '0003_add_submit_date_index'),
        ('retos', '0033_mpttcomment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MPTTComment',
        ),
    ]
