# Generated by Django 3.0.8 on 2020-07-27 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('retos', '0034_delete_mpttcomment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answerchallenge',
            options={'ordering': ('-date',)},
        ),
    ]
