# Generated by Django 3.0.8 on 2020-07-28 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retos', '0035_auto_20200727_2341'),
    ]

    operations = [
        migrations.AddField(
            model_name='answerchallenge',
            name='slug',
            field=models.SlugField(default=True),
        ),
    ]
