# Generated by Django 3.0.8 on 2020-07-28 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('retos', '0036_answerchallenge_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answerchallenge',
            options={},
        ),
    ]
