# Generated by Django 3.0.8 on 2020-07-28 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retos', '0039_auto_20200728_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answerchallenge',
            name='slug',
            field=models.SlugField(default=True, max_length=250, unique_for_date='date'),
        ),
    ]
