# Generated by Django 3.0.8 on 2020-07-28 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('retos', '0041_auto_20200728_2113'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={},
        ),
    ]
