# Generated by Django 3.0.8 on 2020-09-05 16:54

from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('retos', '0043_auto_20200805_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='image',
            field=stdimage.models.StdImageField(upload_to='imag_retos'),
        ),
    ]
